// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Request_Course.Data;

#nullable disable

namespace Request_Course.Migrations
{
    [DbContext(typeof(ReqContexts))]
    [Migration("20230715174220_Create")]
    partial class Create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Request_Course.Models.T_Activation", b =>
                {
                    b.Property<long>("ID_Activation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_Activation"), 1L, 1);

                    b.Property<DateTime?>("DateGenerateCode")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Student")
                        .HasColumnType("bit");

                    b.Property<int?>("T_Modaresan_ID")
                        .HasColumnType("int");

                    b.Property<int?>("T_Mokhatebin_ID")
                        .HasColumnType("int");

                    b.Property<bool>("Teacher")
                        .HasColumnType("bit");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)")
                        .IsFixedLength();

                    b.HasKey("ID_Activation");

                    b.HasIndex("T_Modaresan_ID");

                    b.HasIndex("T_Mokhatebin_ID");

                    b.ToTable("T_Activation");
                });

            modelBuilder.Entity("Request_Course.Models.T_Doreh_Darkhasti", b =>
                {
                    b.Property<int>("ID_Doreh_Darkhasti")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Doreh_Darkhasti"), 1L, 1);

                    b.Property<DateTime?>("Date_Az_Ejra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Az_Pishnahad")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Ta_Ejra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Ta_Pishnahad")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Nomreh_Modares")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("OnvanDoreh_Jadid")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("T_L_MediaAmozeshi_ID")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_ModateDoreh_ID")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_MokhatabanDoreh_ID")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_OnvanAsli_ID")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_OnvanDoreh_ID")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_RaveshAmozeshi_ID")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_SatheKeyfi_Modares_ID")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_Vaziyat_Doreh_ID")
                        .HasColumnType("int");

                    b.Property<int?>("T_Modaresan_ID")
                        .HasColumnType("int");

                    b.Property<int?>("T_Mokhatebin_ID")
                        .HasColumnType("int");

                    b.HasKey("ID_Doreh_Darkhasti");

                    b.HasIndex("T_L_MediaAmozeshi_ID");

                    b.HasIndex("T_L_ModateDoreh_ID");

                    b.HasIndex("T_L_MokhatabanDoreh_ID");

                    b.HasIndex("T_L_OnvanDoreh_ID");

                    b.HasIndex("T_L_RaveshAmozeshi_ID");

                    b.HasIndex("T_L_SatheKeyfi_Modares_ID");

                    b.HasIndex("T_L_Vaziyat_Doreh_ID");

                    b.HasIndex("T_Modaresan_ID");

                    b.HasIndex("T_Mokhatebin_ID");

                    b.ToTable("T_Doreh_Darkhasti");
                });

            modelBuilder.Entity("Request_Course.Models.T_Fasl_Doreh", b =>
                {
                    b.Property<int>("ID_Fasl_Doreh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Fasl_Doreh"), 1L, 1);

                    b.Property<string>("Modate_Ejra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mohtav")
                        .IsRequired()
                        .HasMaxLength(550)
                        .HasColumnType("nvarchar(550)");

                    b.Property<string>("Shekle_Ejra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("T_L_OnvanAsli_ID")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_OnvanDoreh_ID")
                        .HasColumnType("int");

                    b.HasKey("ID_Fasl_Doreh");

                    b.HasIndex("T_L_OnvanAsli_ID");

                    b.HasIndex("T_L_OnvanDoreh_ID");

                    b.ToTable("T_Fasl_Doreh");
                });

            modelBuilder.Entity("Request_Course.Models.T_Fasl_Doreh_Pishnahadi", b =>
                {
                    b.Property<int>("ID_Fasl_Doreh_Pishnahadi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Fasl_Doreh_Pishnahadi"), 1L, 1);

                    b.Property<string>("Modate_Ejra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mohtava")
                        .IsRequired()
                        .HasMaxLength(550)
                        .HasColumnType("nvarchar(550)");

                    b.Property<string>("Shekle_Ejra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("T_Doreh_Darkhasti_ID")
                        .HasColumnType("int");

                    b.HasKey("ID_Fasl_Doreh_Pishnahadi");

                    b.HasIndex("T_Doreh_Darkhasti_ID");

                    b.ToTable("T_Fasl_Doreh_Pishnahadi");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_DaragehElmi", b =>
                {
                    b.Property<int>("ID_DaragehElmi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_DaragehElmi"), 1L, 1);

                    b.Property<string>("Titles_DaragehElmi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_DaragehElmi");

                    b.ToTable("T_L_DaragehElmi");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_FildAsli", b =>
                {
                    b.Property<int>("ID_FildAsli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_FildAsli"), 1L, 1);

                    b.Property<string>("Titles_FildAsli")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ID_FildAsli");

                    b.ToTable("T_L_FildAsli");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_MaghtaeTahsili", b =>
                {
                    b.Property<int>("ID_MaghtaeTahsili")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_MaghtaeTahsili"), 1L, 1);

                    b.Property<string>("Titles_MaghtaeTahsili")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_MaghtaeTahsili");

                    b.ToTable("T_L_MaghtaeTahsili");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_MediaAmozeshi", b =>
                {
                    b.Property<int>("ID_MediaAmozeshi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_MediaAmozeshi"), 1L, 1);

                    b.Property<string>("Titles_MediaAmozeshi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_MediaAmozeshi");

                    b.ToTable("T_L_MediaAmozeshi");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_ModateDoreh", b =>
                {
                    b.Property<int>("ID_ModateDoreh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_ModateDoreh"), 1L, 1);

                    b.Property<string>("Titles_ModateDoreh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_ModateDoreh");

                    b.ToTable("T_L_ModateDoreh");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_MokhatabanDoreh", b =>
                {
                    b.Property<int>("ID_MokhatabanDoreh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_MokhatabanDoreh"), 1L, 1);

                    b.Property<string>("Titles_MokhatabanDoreh")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ID_MokhatabanDoreh");

                    b.ToTable("T_L_MokhatabanDoreh");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_OnvanAsli", b =>
                {
                    b.Property<int>("ID_L_OnvanAsli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_L_OnvanAsli"), 1L, 1);

                    b.Property<string>("Titles_OnvanAsli")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_L_OnvanAsli");

                    b.ToTable("T_L_OnvanAsli");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_OnvanDoreh", b =>
                {
                    b.Property<int>("ID_OnvanDoreh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_OnvanDoreh"), 1L, 1);

                    b.Property<string>("Titles_OnvanDoreh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_OnvanDoreh");

                    b.ToTable("T_L_OnvanDoreh");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_Ostan", b =>
                {
                    b.Property<int>("ID_Ostan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Ostan"), 1L, 1);

                    b.Property<string>("Titles_Ostan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Ostan");

                    b.ToTable("T_L_Ostan");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_RaveshAmozeshi", b =>
                {
                    b.Property<int>("ID_L_RaveshAmozeshi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_L_RaveshAmozeshi"), 1L, 1);

                    b.Property<string>("Titles_RaveshAmozeshi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_L_RaveshAmozeshi");

                    b.ToTable("T_L_RaveshAmozeshi");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_ReshtehTahsili", b =>
                {
                    b.Property<int>("ID_ReshtehTahsili")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_ReshtehTahsili"), 1L, 1);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Titles_ReshtehTahsili")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_ReshtehTahsili");

                    b.ToTable("T_L_ReshtehTahsili");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_Sathe_Sherkat", b =>
                {
                    b.Property<int>("ID_Sathe_Sherkat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Sathe_Sherkat"), 1L, 1);

                    b.Property<string>("Titles_Sathe_Sherkat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Sathe_Sherkat");

                    b.ToTable("T_L_Sathe_Sherkat");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_SatheKeyfi_Modares", b =>
                {
                    b.Property<int>("ID_L_SatheKeyfi_Modares")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_L_SatheKeyfi_Modares"), 1L, 1);

                    b.Property<string>("Titles_SatheKeyfi_Modares")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_L_SatheKeyfi_Modares");

                    b.ToTable("T_L_SatheKeyfi_Modares");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_Semat", b =>
                {
                    b.Property<int>("ID_Semat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Semat"), 1L, 1);

                    b.Property<string>("Titles_Semat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Semat");

                    b.ToTable("T_L_Semat");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_Vaziyat_Doreh", b =>
                {
                    b.Property<int>("ID_L_Vaziyat_Doreh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_L_Vaziyat_Doreh"), 1L, 1);

                    b.Property<string>("Titles_Vaziyat_Doreh")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ID_L_Vaziyat_Doreh");

                    b.ToTable("T_L_Vaziyat_Doreh");
                });

            modelBuilder.Entity("Request_Course.Models.T_MarahelDoreh", b =>
                {
                    b.Property<int>("ID_Marahel_Doreh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Marahel_Doreh"), 1L, 1);

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("T_Doreh_Darkhasti_ID")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_Vaziyat_Doreh_ID")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("ID_Marahel_Doreh");

                    b.HasIndex("T_Doreh_Darkhasti_ID");

                    b.HasIndex("T_L_Vaziyat_Doreh_ID");

                    b.ToTable("T_MarahelDoreh");
                });

            modelBuilder.Entity("Request_Course.Models.T_Modaresan", b =>
                {
                    b.Property<int>("ID_Modaresan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Modaresan"), 1L, 1);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Avg_Nomreh_Tadris")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<int?>("C_Doreh_Ejra")
                        .HasColumnType("int");

                    b.Property<string>("Daneshgah_Sherkat")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MadrakTahsili")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("Nomreh_Keyfi")
                        .HasPrecision(2, 2)
                        .HasColumnType("decimal(2,2)");

                    b.Property<string>("Onvan_Shoghli")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Rotbe_Modares")
                        .HasColumnType("int");

                    b.Property<int?>("Sathe_Keyfi")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_DaragehElmi_ID")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_MaghtaeTahsili_ID")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_ReshtehTahsili_ID")
                        .HasColumnType("int");

                    b.HasKey("ID_Modaresan");

                    b.HasIndex("T_L_DaragehElmi_ID");

                    b.HasIndex("T_L_MaghtaeTahsili_ID");

                    b.HasIndex("T_L_ReshtehTahsili_ID");

                    b.ToTable("T_Modaresan");
                });

            modelBuilder.Entity("Request_Course.Models.T_Modaresan_Fild_Amozeshi", b =>
                {
                    b.Property<int>("ID_Modaresan_Fild_Amozeshi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Modaresan_Fild_Amozeshi"), 1L, 1);

                    b.Property<DateTime?>("Date_Create")
                        .HasColumnType("datetime2");

                    b.Property<int?>("T_L_FildAsli_ID")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_OnvanDoreh_ID")
                        .HasColumnType("int");

                    b.Property<int?>("T_Modaresan_ID")
                        .HasColumnType("int");

                    b.HasKey("ID_Modaresan_Fild_Amozeshi");

                    b.HasIndex("T_L_FildAsli_ID");

                    b.HasIndex("T_L_OnvanDoreh_ID");

                    b.HasIndex("T_Modaresan_ID");

                    b.ToTable("T_Modaresan_Fild_Amozeshi");
                });

            modelBuilder.Entity("Request_Course.Models.T_Mokhatebin", b =>
                {
                    b.Property<int>("ID_Mokhatebin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Mokhatebin"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Mobile_Rabet")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("NamFamily_Rabet")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name_Sherkat")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("T_L_Ostan_ID")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_Sathe_Sherkat_ID")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_Semat_ID")
                        .HasColumnType("int");

                    b.HasKey("ID_Mokhatebin");

                    b.HasIndex("T_L_Ostan_ID");

                    b.HasIndex("T_L_Sathe_Sherkat_ID");

                    b.HasIndex("T_L_Semat_ID");

                    b.ToTable("T_Mokhatebin");
                });

            modelBuilder.Entity("Request_Course.Models.T_Nazarsanji", b =>
                {
                    b.Property<int>("ID_Nazarsanji")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Nazarsanji"), 1L, 1);

                    b.Property<decimal?>("Avg_Num")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Num_Roayat_Nazm")
                        .HasColumnType("int");

                    b.Property<int?>("Num_Roayat_Sarfasl")
                        .HasColumnType("int");

                    b.Property<int?>("Num_TamoolBaFaragir")
                        .HasColumnType("int");

                    b.Property<int?>("Num_Tasalot")
                        .HasColumnType("int");

                    b.Property<int?>("T_Doreh_Darkhasti_ID")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("ID_Nazarsanji");

                    b.HasIndex("T_Doreh_Darkhasti_ID");

                    b.ToTable("T_Nazarsanji");
                });

            modelBuilder.Entity("Request_Course.Models.T_Pishnahad_Modares_Doreh", b =>
                {
                    b.Property<int>("ID_Pishnahad_Modares_Doreh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Pishnahad_Modares_Doreh"), 1L, 1);

                    b.Property<string>("Pishnahad_Modares_Name1")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Pishnahad_Modares_Name2")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Pishnahad_Modares_Name3")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Pishnahad_Modares_phone1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pishnahad_Modares_phone2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pishnahad_Modares_phone3")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("T_Doreh_Darkhasti_ID")
                        .HasColumnType("int");

                    b.Property<int?>("T_Modaresan_ID1")
                        .HasColumnType("int");

                    b.Property<int?>("T_Modaresan_ID2")
                        .HasColumnType("int");

                    b.Property<int?>("T_Modaresan_ID3")
                        .HasColumnType("int");

                    b.HasKey("ID_Pishnahad_Modares_Doreh");

                    b.HasIndex("T_Doreh_Darkhasti_ID");

                    b.HasIndex("T_Modaresan_ID1");

                    b.HasIndex("T_Modaresan_ID2");

                    b.HasIndex("T_Modaresan_ID3");

                    b.ToTable("T_Pishnahad_Modares_Doreh");
                });

            modelBuilder.Entity("Request_Course.Models.T_Activation", b =>
                {
                    b.HasOne("Request_Course.Models.T_Modaresan", "T_Modaresan")
                        .WithMany("T_Activation")
                        .HasForeignKey("T_Modaresan_ID");

                    b.HasOne("Request_Course.Models.T_Mokhatebin", "T_Mokhatebin")
                        .WithMany("T_Activation")
                        .HasForeignKey("T_Mokhatebin_ID");

                    b.Navigation("T_Modaresan");

                    b.Navigation("T_Mokhatebin");
                });

            modelBuilder.Entity("Request_Course.Models.T_Doreh_Darkhasti", b =>
                {
                    b.HasOne("Request_Course.Models.T_L_MediaAmozeshi", "T_L_MediaAmozeshi")
                        .WithMany("T_Doreh_Darkhasti")
                        .HasForeignKey("T_L_MediaAmozeshi_ID");

                    b.HasOne("Request_Course.Models.T_L_ModateDoreh", "T_L_ModateDoreh")
                        .WithMany("T_Doreh_Darkhasti")
                        .HasForeignKey("T_L_ModateDoreh_ID");

                    b.HasOne("Request_Course.Models.T_L_MokhatabanDoreh", "T_L_MokhatabanDoreh")
                        .WithMany("T_Doreh_Darkhasti")
                        .HasForeignKey("T_L_MokhatabanDoreh_ID");

                    b.HasOne("Request_Course.Models.T_L_OnvanDoreh", "T_L_OnvanDoreh")
                        .WithMany("T_Doreh_Darkhasti")
                        .HasForeignKey("T_L_OnvanDoreh_ID");

                    b.HasOne("Request_Course.Models.T_L_RaveshAmozeshi", "T_L_RaveshAmozeshi")
                        .WithMany("T_Doreh_Darkhasti")
                        .HasForeignKey("T_L_RaveshAmozeshi_ID");

                    b.HasOne("Request_Course.Models.T_L_SatheKeyfi_Modares", "T_L_SatheKeyfi_Modares")
                        .WithMany("T_Doreh_Darkhasti")
                        .HasForeignKey("T_L_SatheKeyfi_Modares_ID");

                    b.HasOne("Request_Course.Models.T_L_Vaziyat_Doreh", "T_L_Vaziyat_Doreh")
                        .WithMany("T_Doreh_Darkhasti")
                        .HasForeignKey("T_L_Vaziyat_Doreh_ID");

                    b.HasOne("Request_Course.Models.T_Modaresan", "T_Modaresan")
                        .WithMany("T_Doreh_Darkhasti")
                        .HasForeignKey("T_Modaresan_ID");

                    b.HasOne("Request_Course.Models.T_Mokhatebin", "T_Mokhatebin")
                        .WithMany("T_Doreh_Darkhasti")
                        .HasForeignKey("T_Mokhatebin_ID");

                    b.Navigation("T_L_MediaAmozeshi");

                    b.Navigation("T_L_ModateDoreh");

                    b.Navigation("T_L_MokhatabanDoreh");

                    b.Navigation("T_L_OnvanDoreh");

                    b.Navigation("T_L_RaveshAmozeshi");

                    b.Navigation("T_L_SatheKeyfi_Modares");

                    b.Navigation("T_L_Vaziyat_Doreh");

                    b.Navigation("T_Modaresan");

                    b.Navigation("T_Mokhatebin");
                });

            modelBuilder.Entity("Request_Course.Models.T_Fasl_Doreh", b =>
                {
                    b.HasOne("Request_Course.Models.T_L_OnvanAsli", "T_L_OnvanAsli")
                        .WithMany("T_Fasl_Doreh")
                        .HasForeignKey("T_L_OnvanAsli_ID");

                    b.HasOne("Request_Course.Models.T_L_OnvanDoreh", "T_L_OnvanDoreh")
                        .WithMany("T_Fasl_Doreh")
                        .HasForeignKey("T_L_OnvanDoreh_ID");

                    b.Navigation("T_L_OnvanAsli");

                    b.Navigation("T_L_OnvanDoreh");
                });

            modelBuilder.Entity("Request_Course.Models.T_Fasl_Doreh_Pishnahadi", b =>
                {
                    b.HasOne("Request_Course.Models.T_Doreh_Darkhasti", "T_Doreh_Darkhasti")
                        .WithMany("T_Fasl_Doreh_Pishnahadi")
                        .HasForeignKey("T_Doreh_Darkhasti_ID");

                    b.Navigation("T_Doreh_Darkhasti");
                });

            modelBuilder.Entity("Request_Course.Models.T_MarahelDoreh", b =>
                {
                    b.HasOne("Request_Course.Models.T_Doreh_Darkhasti", "T_Doreh_Darkhasti")
                        .WithMany("T_MarahelDoreh")
                        .HasForeignKey("T_Doreh_Darkhasti_ID");

                    b.HasOne("Request_Course.Models.T_L_Vaziyat_Doreh", "T_L_Vaziyat_Doreh")
                        .WithMany("T_MarahelDoreh")
                        .HasForeignKey("T_L_Vaziyat_Doreh_ID");

                    b.Navigation("T_Doreh_Darkhasti");

                    b.Navigation("T_L_Vaziyat_Doreh");
                });

            modelBuilder.Entity("Request_Course.Models.T_Modaresan", b =>
                {
                    b.HasOne("Request_Course.Models.T_L_DaragehElmi", "T_L_DaragehElmi")
                        .WithMany("T_Modaresan")
                        .HasForeignKey("T_L_DaragehElmi_ID");

                    b.HasOne("Request_Course.Models.T_L_MaghtaeTahsili", "T_L_MaghtaeTahsili")
                        .WithMany("T_Modaresan")
                        .HasForeignKey("T_L_MaghtaeTahsili_ID");

                    b.HasOne("Request_Course.Models.T_L_ReshtehTahsili", "T_L_ReshtehTahsili")
                        .WithMany("T_Modaresan")
                        .HasForeignKey("T_L_ReshtehTahsili_ID");

                    b.Navigation("T_L_DaragehElmi");

                    b.Navigation("T_L_MaghtaeTahsili");

                    b.Navigation("T_L_ReshtehTahsili");
                });

            modelBuilder.Entity("Request_Course.Models.T_Modaresan_Fild_Amozeshi", b =>
                {
                    b.HasOne("Request_Course.Models.T_L_FildAsli", "T_L_FildAsli")
                        .WithMany("T_Modaresan_Fild_Amozeshi")
                        .HasForeignKey("T_L_FildAsli_ID");

                    b.HasOne("Request_Course.Models.T_L_OnvanDoreh", "T_L_OnvanDoreh")
                        .WithMany("T_Modaresan_Fild_Amozeshi")
                        .HasForeignKey("T_L_OnvanDoreh_ID");

                    b.HasOne("Request_Course.Models.T_Modaresan", "T_Modaresan")
                        .WithMany("T_Modaresan_Fild_Amozeshi")
                        .HasForeignKey("T_Modaresan_ID");

                    b.Navigation("T_L_FildAsli");

                    b.Navigation("T_L_OnvanDoreh");

                    b.Navigation("T_Modaresan");
                });

            modelBuilder.Entity("Request_Course.Models.T_Mokhatebin", b =>
                {
                    b.HasOne("Request_Course.Models.T_L_Ostan", "T_L_Ostan")
                        .WithMany("T_Mokhatebin")
                        .HasForeignKey("T_L_Ostan_ID");

                    b.HasOne("Request_Course.Models.T_L_Sathe_Sherkat", "T_L_Sathe_Sherkat")
                        .WithMany("T_Mokhatebin")
                        .HasForeignKey("T_L_Sathe_Sherkat_ID");

                    b.HasOne("Request_Course.Models.T_L_Semat", "T_L_Semat")
                        .WithMany("T_Mokhatebin")
                        .HasForeignKey("T_L_Semat_ID");

                    b.Navigation("T_L_Ostan");

                    b.Navigation("T_L_Sathe_Sherkat");

                    b.Navigation("T_L_Semat");
                });

            modelBuilder.Entity("Request_Course.Models.T_Nazarsanji", b =>
                {
                    b.HasOne("Request_Course.Models.T_Doreh_Darkhasti", "T_Doreh_Darkhasti")
                        .WithMany("T_Nazarsanji")
                        .HasForeignKey("T_Doreh_Darkhasti_ID");

                    b.Navigation("T_Doreh_Darkhasti");
                });

            modelBuilder.Entity("Request_Course.Models.T_Pishnahad_Modares_Doreh", b =>
                {
                    b.HasOne("Request_Course.Models.T_Doreh_Darkhasti", "T_Doreh_Darkhasti")
                        .WithMany("T_Pishnahad_Modares_Doreh")
                        .HasForeignKey("T_Doreh_Darkhasti_ID");

                    b.HasOne("Request_Course.Models.T_Modaresan", "T_Modaresan")
                        .WithMany("T_Pishnahad_Modares_Doreh")
                        .HasForeignKey("T_Modaresan_ID1");

                    b.HasOne("Request_Course.Models.T_Mokhatebin", "T_Mokhatebin")
                        .WithMany("T_Pishnahad_Modares_Doreh")
                        .HasForeignKey("T_Modaresan_ID2");

                    b.HasOne("Request_Course.Models.T_Mokhatebin", "T_Mokhatebin1")
                        .WithMany("T_Pishnahad_Modares_Doreh1")
                        .HasForeignKey("T_Modaresan_ID3");

                    b.Navigation("T_Doreh_Darkhasti");

                    b.Navigation("T_Modaresan");

                    b.Navigation("T_Mokhatebin");

                    b.Navigation("T_Mokhatebin1");
                });

            modelBuilder.Entity("Request_Course.Models.T_Doreh_Darkhasti", b =>
                {
                    b.Navigation("T_Fasl_Doreh_Pishnahadi");

                    b.Navigation("T_MarahelDoreh");

                    b.Navigation("T_Nazarsanji");

                    b.Navigation("T_Pishnahad_Modares_Doreh");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_DaragehElmi", b =>
                {
                    b.Navigation("T_Modaresan");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_FildAsli", b =>
                {
                    b.Navigation("T_Modaresan_Fild_Amozeshi");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_MaghtaeTahsili", b =>
                {
                    b.Navigation("T_Modaresan");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_MediaAmozeshi", b =>
                {
                    b.Navigation("T_Doreh_Darkhasti");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_ModateDoreh", b =>
                {
                    b.Navigation("T_Doreh_Darkhasti");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_MokhatabanDoreh", b =>
                {
                    b.Navigation("T_Doreh_Darkhasti");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_OnvanAsli", b =>
                {
                    b.Navigation("T_Fasl_Doreh");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_OnvanDoreh", b =>
                {
                    b.Navigation("T_Doreh_Darkhasti");

                    b.Navigation("T_Fasl_Doreh");

                    b.Navigation("T_Modaresan_Fild_Amozeshi");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_Ostan", b =>
                {
                    b.Navigation("T_Mokhatebin");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_RaveshAmozeshi", b =>
                {
                    b.Navigation("T_Doreh_Darkhasti");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_ReshtehTahsili", b =>
                {
                    b.Navigation("T_Modaresan");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_Sathe_Sherkat", b =>
                {
                    b.Navigation("T_Mokhatebin");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_SatheKeyfi_Modares", b =>
                {
                    b.Navigation("T_Doreh_Darkhasti");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_Semat", b =>
                {
                    b.Navigation("T_Mokhatebin");
                });

            modelBuilder.Entity("Request_Course.Models.T_L_Vaziyat_Doreh", b =>
                {
                    b.Navigation("T_Doreh_Darkhasti");

                    b.Navigation("T_MarahelDoreh");
                });

            modelBuilder.Entity("Request_Course.Models.T_Modaresan", b =>
                {
                    b.Navigation("T_Activation");

                    b.Navigation("T_Doreh_Darkhasti");

                    b.Navigation("T_Modaresan_Fild_Amozeshi");

                    b.Navigation("T_Pishnahad_Modares_Doreh");
                });

            modelBuilder.Entity("Request_Course.Models.T_Mokhatebin", b =>
                {
                    b.Navigation("T_Activation");

                    b.Navigation("T_Doreh_Darkhasti");

                    b.Navigation("T_Pishnahad_Modares_Doreh");

                    b.Navigation("T_Pishnahad_Modares_Doreh1");
                });
#pragma warning restore 612, 618
        }
    }
}
